controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_controller:
  ros__parameters:
    reference_timeout: 0.5

    front_left_wheel_command_joint_name: front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name: rear_left_wheel_joint
    rear_right_wheel_command_joint_name: rear_right_wheel_joint
    front_left_wheel_state_joint_name: front_left_wheel_joint
    front_right_wheel_state_joint_name: front_right_wheel_joint
    rear_left_wheel_state_joint_name: rear_left_wheel_joint
    rear_right_wheel_state_joint_name: rear_right_wheel_joint

    kinematics:
      base_frame_offset: {x: 0.0, y: 0.0, theta: 0.0}
      wheels_radius: 0.05
      # lx + ly, where wheels are at (x=0.20, y=0.15) from center => 0.35
      sum_of_robot_center_projection_on_X_Y_axis: 0.35

    use_stamped_vel: true
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
